---
- hosts: myWebServers
  become: yes
  tasks:
  - name: install open jdk8 on ubuntu 
    apt:
      name: "{{myjavapackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: install open jdk8 on ReHat
    yum:
      name: "{{myjavapackonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"
