---
- hosts: all
  become: yes  # sudo apt-get inatall git
  tasks: 
  - name: i want to install tree  on ansible node
    apt:
      name: tree
      state: present
  - name: i want to install wget on ansible node 
    apt:
      name: wget
      state: present

  - name: i want to insall git on ansible node
    apt:
      name: git
      state: present